##### Admin CMS APIs


### root api
GET http://localhost:8000/


### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Sagar",
    "lname": "Pyakurel",
    "email": "sagar@gmail.com",
    "password": "Sagardasdasd",
    "phone": "123456",
    "address": "Sydney, NSW",
    "gender" : "male"

  

}




### verify admin email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "153165",
    "email": "sagar@gmail.com"
}




#Catalog router
### Get all or single category
GET http://localhost:8000/api/v1/catalog/



### Create new category 
POST http://localhost:8000/api/v1/catalog 
Content-Type: application/json

{
    "name": "Monitors ",
  "parentCat" :"6199a67e4fc1e897c79894d1" 
}


### Delete Category 
DELETE http://localhost:8000/api/v1/catalog/6199c6ef10f2fb9390430a29


### update category 
PATCH  http://localhost:8000/api/v1/catalog 
Content-Type: application/json

{
    "_id" : "6199c653509d07979ada8362",
    "name": "sagar",
  "parentCat" : null 
}
