##### Admin CMS APIs


### root api
GET http://localhost:8000/


### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Sagar",
    "lname": "Pyakurel",
    "email": "sagar@gmail.com",
    "password": "Sagardasdasd",
    "phone": "123456",
    "address": "Sydney, NSW",
    "gender" : "male"

  

}




### verify admin email
PATCH  http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "pin": "153165",
    "email": "sagar@gmail.com"
}
