##### Admin CMS APIs


### root api
GET http://localhost:8000/


### Create new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname": "Sagar",
    "lname": "Pyakurel",
    "email": "sas@gmail.com",
    "password": "Sagardasdasd",
    "phone": "123456",
    "address": "Sydney, NSW",
    "gender" : "male"

  

}


